# Generated by Django 3.1.2 on 2020-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cussel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesorg', models.CharField(max_length=50)),
                ('importzone', models.CharField(max_length=50)),
                ('soldto', models.CharField(max_length=50)),
                ('shipto', models.CharField(max_length=50)),
                ('shiptoname', models.CharField(max_length=50)),
                ('shiptocountry', models.CharField(max_length=50)),
                ('shipcond', models.CharField(max_length=15)),
                ('payer', models.CharField(max_length=50)),
                ('payername', models.CharField(max_length=50)),
                ('profitcen', models.CharField(max_length=50)),
                ('incoterm', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('attri', models.CharField(max_length=50)),
            ],
        ),
    ]
