# Generated by Django 3.1.2 on 2020-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_portal', '0002_cussel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15)),
                ('matdesc', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=15)),
                ('contsize', models.CharField(max_length=15)),
                ('secondpack', models.CharField(max_length=15)),
            ],
        ),
    ]
